# Generated by Django 3.0.4 on 2020-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptedDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('breed', models.CharField(max_length=150)),
                ('adopt_date', models.DateField()),
                ('birth_year', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
    ]
