# Generated by Django 3.0.4 on 2020-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='adopted',
            field=models.CharField(choices=[('adoptable', 'Adoptable'), ('adopted', 'Adopted')], default='adoptable', max_length=15),
        ),
    ]
