# Generated by Django 3.0.4 on 2020-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_auto_20200506_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='adopted',
            field=models.CharField(choices=[('adopted', 'Igen'), ('adoptable', 'Nem')], default='adoptable', max_length=15, verbose_name='Örökbeadott?'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birth_year',
            field=models.IntegerField(choices=[('ismeretlen', 'Ismeretlen'), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], verbose_name='Születési év'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='body',
            field=models.TextField(verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Keverék', max_length=150, verbose_name='Fajta'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='income_date',
            field=models.DateField(verbose_name='Felvételi év'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='dogimages',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Képek'),
        ),
    ]
