# Generated by Django 3.0.4 on 2020-05-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_auto_20200506_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name_plural': 'Kutyák'},
        ),
        migrations.AlterModelOptions(
            name='dogimages',
            options={'verbose_name_plural': 'Képek a kutyáról'},
        ),
        migrations.AlterModelTable(
            name='dog',
            table='Kutyák',
        ),
    ]
