# Generated by Django 3.0.4 on 2020-05-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_auto_20200506_1409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='Kutyak',
        ),
    ]
