# Generated by Django 3.0.4 on 2020-05-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_auto_20200506_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dogimages',
            options={},
        ),
        migrations.AlterModelTable(
            name='dog',
            table=None,
        ),
    ]
