# Generated by Django 3.0.4 on 2020-05-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_auto_20200512_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name_plural': 'Kutyák'},
        ),
    ]
