# Generated by Django 3.0.4 on 2020-05-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0014_auto_20200512_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogimages',
            options={'verbose_name_plural': 'Képek a kutyáról'},
        ),
        migrations.AlterModelTable(
            name='dog',
            table=None,
        ),
    ]
