# Generated by Django 3.0.4 on 2020-05-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0015_auto_20200512_1316'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='Kutyák',
        ),
    ]
