# Generated by Django 3.0.4 on 2020-05-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0016_auto_20200512_1321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table=None,
        ),
    ]
