# Generated by Django 3.0.4 on 2020-04-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200414_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image',
            new_name='main_image',
        ),
        migrations.CreateModel(
            name='StoryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Story')),
            ],
        ),
    ]
